version: '2'
volumes:
  php-dev-data: {}
services:
  php-dev-debian-jessie:
    container_name: php-dev-debian-jessie
    hostname: php-dev-debian-jessie
    build:
      context: ../
      dockerfile: containers/php-dev-debian-jessie/Dockerfile
    image: php-dev:debian-jessie
    volumes:
      - ../sites:/var/www
      - ../databases:/var/databases
      - ../vhosts:/etc/apache2/sites-enabled
      - php-dev-data:/var/lib/mysql
    ports:
      - "80:80"
      - "8025:8025"
